config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
    username: nacos
    password: nacos

spring:
  cloud:
    nacos:
      username: ${config.nacos.username}
      password: ${config.nacos.password}
      discovery:
        server-addr: ${config.nacos.host}
        namespace: public
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/badger?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root

dubbo:
  protocol:
    name: dubbo
    port: 29941
  application:
    name: dubbo-badger-id-generator-provider
    qos-enable: false
  registry:
    address: nacos://${config.nacos.host}?namespace=public&username=${config.nacos.username}&password=${config.nacos.password}