config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
    username: nacos
    password: nacos

spring:
  cloud:
    nacos:
      username: ${config.nacos.username}
      password: ${config.nacos.password}
      discovery:
        server-addr: ${config.nacos.host}
        namespace: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/badger?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:127.0.0.1}
      database: 0
      lettuce:
        pool:
          min-idle: 1
          max-idle: 5
          max-active: 10

dubbo:
  protocol:
    name: dubbo
    port: 29951
  application:
    name: dubbo-badger-sms-provider
    qos-enable: false
  registry:
    address: nacos://${config.nacos.host}?namespace=dev&username=${config.nacos.username}&password=${config.nacos.password}