CREATE TABLE `schema_change_audit` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `logic_table` varchar(128) NOT NULL,
  `column_name` varchar(128) NOT NULL,
  `ddl_template` varchar(1000) NOT NULL,
  `rollback_sqls` longtext,
  `request_payload` longtext,
  `report_payload` longtext,
  `status` varchar(64) NOT NULL,
  `status_message` varchar(1000) DEFAULT NULL,
  `dry_run` tinyint NOT NULL DEFAULT '0',
  `executed` tinyint NOT NULL DEFAULT '0',
  `full_sync_confirmed` tinyint NOT NULL DEFAULT '0',
  `physical_table_count` int DEFAULT NULL,
  `sharding_config_source` varchar(255) DEFAULT NULL,
  `operator_id` bigint DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `finish_time` datetime NOT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_logic_table_column` (`logic_table`,`column_name`),
  KEY `idx_status_create_time` (`status`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
